#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
cookbook 'apache2'
cookbook 'apt'
cookbook 'ant'
cookbook 'git'
cookbook 'vim' 
cookbook 'zip'
#cookbook 'jenkins'
#cookbook 'jenkins', :git => 'https://github.com/opscode-cookbooks/jenkins.git'
cookbook 'jenkins', :git => 'https://github.com/fnichol/chef-jenkins.git'

cookbook 'ubuntu'
cookbook 'mysql'
#cookbook 'postgresql '
cookbook 'coldfusion10', :git => 'https://github.com/wharton/chef-coldfusion10.git'
cookbook 'mxunit', :git => 'https://github.com/wharton/chef-mxunit.git'
cookbook 'cloudy', :git => 'https://github.com/mhenke/Cloudy-With-A-Chance-Of-Tests-Chef.git'
#cookbook 'varscoper', :git => 'https://github.com/mhenke/chef-varscoper.git'
#cookbook 'cfqueryparam', :git => 'https://github.com/mhenke/chef-cfqueryparam.git'
cookbook 'java'
#cookbook 'rng-tools'