#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
cookbook 'apache2'
cookbook 'apt'
cookbook 'ant'
cookbook 'ark',"0.1.0"
cookbook 'coldfusion10', :git => 'https://github.com/wharton/chef-coldfusion10.git'
cookbook 'java'
cookbook 'git'
cookbook 'vim' 
cookbook 'zip'
cookbook 'mxunit', :git => 'https://github.com/wharton/chef-mxunit.git'
cookbook 'cloudy', :git => 'https://github.com/mhenke/Cloudy-With-A-Chance-Of-Tests-Chef.git'
cookbook 'varscoper', :git => 'https://github.com/mhenke/chef-varscoper.git'
cookbook 'qpscanner', :git => 'https://github.com/mhenke/chef-cfqueryparam.git'
cookbook 'CFSelenium', :git => 'https://github.com/mhenke/chef-cfselenium.git'