#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
cookbook 'apache2'
cookbook 'apt'
cookbook 'ant'
cookbook 'git'
cookbook 'vim'
cookbook 'zip'
cookbook 'coldfusion10', :git => 'https://github.com/wharton/chef-coldfusion10.git'
cookbook 'mxunit', :git => 'https://github.com/wharton/chef-mxunit.git'
cookbook 'cloudy', :git => 'https://github.com/mhenke/Cloudy-With-A-Chance-Of-Tests-Chef.git'
cookbook 'java'
cookbook 'rng-tools'